### ISSUE TITLE
CODE Archetype to create project and bundle

### ISSUE THREAD

**Issue by dzuluagaapigee** [apigee/apigee-deploy-maven-plugin#10]
Based on a conversation with @sriki77, @Priyanky, @rakeshtl it'd be nice to have an artifact utility for:
- [ ] Initializing the project for instance `mvn initialize project-name` creates the basic structure for the project following standards
- [ ] Initializing api proxy bundles `mvn initproxy proxy-name` creates the basic api bundle structure

**Comment by ssvaidyanathan** [comment]
marking as invalid as its out of scope for this plugin as this is mainly focussed on packaging and deploying
