### ISSUE TITLE
update implementation of SharedFlow corrupts the sharedFlow in that environment

### ISSUE THREAD

**Issue by hisureshk** [apigee/apigee-deploy-maven-plugin#103]
When we invoke the deployment of an existing shared-flow in an environment results into corrupt deployment and further query to get the version of the deployment version of shared-flow results into empty.

Steps to reproduce:
1. Deploy a new shared-flow results into success. and query the shared-flow revision will result to 1.

2.  Update the shared-flow deployment results into success and query after deployment the shared-flow revision will result to empty.

3. Re-run the update the shared-flow deployment results into success with version as 2. This is due to query prior to deployment is resulting into empty and apigee assumes there is no version exists. But after deployment the shared-flow revision will result into 2.

Environment Tested: 
On-Premise Apigee 4.18.05

Maven Plugin Tested:
Latest version 1.1.7

Potential Reason:
Maven Plugin uses the same API to update both proxy and shared-flow using type parameter but in the official documentation there is update Proxy API and the same does not exists for shared-flows.

**Comment by ssvaidyanathan** [comment]
Dont think this is a plugin issue. This could be an issue with the Apigee Management server. I believe there was fix for this in the future release.

Closing this issue as its not plugin related
