### ISSUE TITLE
Proxies not assigning to a role, while deploying using maven plugin

### ISSUE THREAD

**Issue by naren1428** [apigee/apigee-deploy-maven-plugin#107]
we are trying to deploy using a machine user assigned to a specific role. after deploying, the proxy is not associating with the role as it associates while we use UI to create a proxy

**Comment by ssvaidyanathan** [comment]
Few things @naren1428 
- This is not a plugin issue
- UI manipulates a bunch of other Management API calls, so it automatically tags the custom role to the proxy

To fix this issue, you can change the machine user role to Org Admin (like many others have). Deploy the proxy using this user and then using the Management API, set the permissions to the custom role to access that proxy

[Add Permissions to Custom Role](https://apidocs.apigee.com/management/apis/post/organizations/%7Borg_name%7D/userroles/%7Brole_name%7D/permissions)

```
{
  "path" : "/applications/{proxy_name}",
  "permissions" : [ "put", "get", "delete" ]
}
```

**Comment by ssvaidyanathan** [comment]
I am closing this issue as its not related to the plugin.
