### ISSUE TITLE
Support for hybrid GA

### ISSUE THREAD

**Issue by kurtkanaskie** [apigee/apigee-deploy-maven-plugin#108]

**Comment by kurtkanaskie** [comment]
Using an external JWT token retrieved via "oauth2l" docs does not work as the plugin is expecting certain claims on the JWT.
Ex: `oauth2l fetch --credentials creds.json --type jwt --audience https://apigee.googleapis.com/
See: https://docs.apigee.com/hybrid/beta2/reference/apis#oauth20

**Comment by ssvaidyanathan** [comment]
Available in version 2.0.0
Checkout the samples from [here](https://github.com/apigee/apigee-deploy-maven-plugin/tree/hybrid/samples)
