### ISSUE TITLE
Does the plugin support SAML+OAuth authentication mechanism rather than basic?

### ISSUE THREAD

**Issue by aishwaryaeswaran** [apigee/apigee-deploy-maven-plugin#111]
Hi,

I am trying to deploy API proxy using the apigee-deploy-maven-plugin. The Apigee platform that I am trying to deploy is a private SaaS offering, which has been integrated with SAML and has basic authentication disabled. Today, to deploy proxy in the Apigee platform, I obtain a one-time passcode, then an OAuth access token and then can use this token in my requests to hit the required APIs. How can I do the same here? Does this plugin support SAML+OAuth authentication mechanism? Thanks!

Reference: https://docs.apigee.com/api-platform/system-administration/using-saml#get-access-tokens-with-get_token

Regards,

**Comment by ssvaidyanathan** [comment]
HI @aishwaryaeswaran 
Check out this [link](https://github.com/apigee/apigee-deploy-maven-plugin#using-oauth) that talks about using oauth with this plugin. There are two options

- Generate the token using the command line you shared and then pass the token to the mvn command. There are profile attributes. Check [this](https://github.com/apigee/apigee-deploy-maven-plugin#using-oauth) 
- Set up a machine user as documented [here](https://docs.apigee.com/api-platform/system-administration/automating-tasks#machiner). With that, you can configure that username and password in the pom file. The plugin will use those credentials to generate a token and complete the deployment. With the machine user, you do not need the passcode flow

Hope that helps

**Comment by aishwaryaeswaran** [comment]
Great, thanks!
