### ISSUE TITLE
The links to sample parent pom and child poms appear to be broken

### ISSUE THREAD

**Issue by ahemanna** [apigee/apigee-deploy-maven-plugin#115]
The links to sample parent pom and child pom under the section [Step 2 Create and configure pom files](https://github.com/apigee/apigee-deploy-maven-plugin#step-2-create-and-configure-pom-files) appears to be broken. It's taking to a 404 github page.

Can we please have this fixed.

**Comment by ssvaidyanathan** [comment]
Fixed the links. Thanks
