### ISSUE TITLE
Fix the code in forecast weather api

### ISSUE THREAD

**Issue by sriki77** [apigee/apigee-deploy-maven-plugin#12]
The proxy code needs to be cleaned up in the sample. Fix naming conventions for policy files, remove unused tags etc.

**Comment by ericdahl** [comment]
some cleanup has been done in pull request https://github.com/apigee/apigee-deploy-maven-plugin/pull/34 (currently open)

**Comment by ssvaidyanathan** [comment]
Fixed #113
