### ISSUE TITLE
Service Account file is missing

### ISSUE THREAD

**Issue by SGoutami** [apigee/apigee-deploy-maven-plugin#129]
Hi ,

Can you help with the below error.

=============Initializing Maven Deployment================

[INFO] 

=============Importing App================

[ERROR] Service Account file is missing
[ERROR] Service Account file is missing
[ERROR] 

* * * * * * * * * * *

This deployment could have failed for a variety of reasons.

**Comment by SGoutami** [comment]
to add to the above issue creation:

the bundle is successfully getting uploaded to apigee edge but because of the error it is not getting deployed

**Comment by ssvaidyanathan** [comment]
@SGoutami - is this still an issue ? I see you have closed the issue ? Are you using the hybrid version of Apigee ?

**Comment by SGoutami** [comment]
I am using apigee edge. the error was caused was due to httptargetconnection configuration in the code, which is now resolved.
