### ISSUE TITLE
Missing dash between the artifact name and the version

### ISSUE THREAD

**Issue by ruettimac** [apigee/apigee-deploy-maven-plugin#13]
Normally, there is a dash in between the artifact name and the version. Normally means, that you will not found any artifacts wihtout this naming pattern. Currently, the artifacts will be created like this:

forecastweatherapi1.0-test.zip

But it should be:

forecastweatherapi-1.0-test.zip

**Comment by ssvaidyanathan** [comment]
v1.2 refactoring fixed this issue
