### ISSUE TITLE
Allow deletion of proxy bundles on Apigee Hybrid

### ISSUE THREAD

**Issue by cerasmus** [apigee/apigee-deploy-maven-plugin#130]
As an API proxy developer
I would like to be able to delete proxies with the hybrid version of the plugin
In the 2.0.0 release for the hybrid plugin all the `${apigee.options}` were removed (except for `override`).
I'd like to be able to do `clean` or `delete`.

The use case is for CI/CD integration testing of proxies. During CI/CD testing pipelines, I would like to be able to: deploy a proxy bundle, perform integration testing and then delete/remove the proxy.

**Comment by ssvaidyanathan** [comment]
@cerasmus - do you mean delete the proxy itself or just the revision that was deployed ?

**Comment by cerasmus** [comment]
Delete the proxy itself. Essentially I want an "ephemeral" proxy. Note, multiple revision may be deployed since I'll likely have a case were different base paths exist for the same proxy bundle. The existing plugin code assume a single revision.

**Comment by ssvaidyanathan** [comment]
In hybrid, the revisions are immutable. If you make a change and deploy its always a new revision.
Hence I was asking if you were looking to delete the proxy itself or the revision. Looks like you are looking to delete the proxy itself.

**Comment by cerasmus** [comment]
Correct. In practice I don't see a need for us to delete revisions. We will either remove a proxy all-together or keep bumping the revision.

**Comment by ssvaidyanathan** [comment]
Cool - will keep you posted

**Comment by ssvaidyanathan** [comment]
v2.0.3 has a new option called `clean`
In hybrid - all the environments should be in undeployed status before the proxy can be deleted.
