### ISSUE TITLE
multiple config file 

### ISSUE THREAD

**Issue by SGoutami** [apigee/apigee-deploy-maven-plugin#131]
how to have a multiple config file for multiple orgs(for eg. dev/test) so that we can check in all the config files to Git for a project in the same place and then use the org specific config file while deploying?

**Comment by SGoutami** [comment]
@ssvaidyanathan  any comments on the above scenario?

**Comment by ssvaidyanathan** [comment]
@SGoutami - are you referring to the configurations like Cache, Targetserver, etc ? if yes, then you should use [apigee-config-maven-plugin](https://github.com/apigee/apigee-config-maven-plugin). You can check the samples in that repo for more info. Please open a GitHub issue in that repo if you find any issue. Closing this issue as its not related to this plugin
