### ISSUE TITLE
Deployment of proxies are failing after upgrading to 2.0.1 and above

### ISSUE THREAD

**Issue by harmeetsra** [apigee/apigee-deploy-maven-plugin#136]
Hello There,

I am currently using version 1.1.7 of plugin. I am trying to upgrade to 2.0.3 and after that it's started failing with below error
[my-folder] [DEBUG]   (f) deploymentEnv = envname
[my-folder] [DEBUG]   (f) hostURL = https://***************
[my-folder] [DEBUG]   (s) id = ******
[my-folder] [DEBUG]   (s) options = override
[my-folder] [DEBUG]   (f) orgName = *****
[my-folder] [DEBUG]   (s) overridedelay = 15
[my-folder] [DEBUG]   (f) password = ****
[my-folder] [DEBUG]   (f) projectName = apiname
[my-folder] [DEBUG]   (f) projectVersion = 1.0
[my-folder] [DEBUG]   (s) skip = false
[my-folder] [DEBUG]   (f) tokenURL = https://login.apigee.com/oauth/token
[my-folder] [DEBUG]   (f) userName = ****
[my-folder] [DEBUG] -- end configuration --
[my-folder] [INFO] 
[my-folder] 
[my-folder] =============Initializing Maven Deployment================
[my-folder] 
[my-folder] 
[my-folder] [INFO] 
[my-folder] 
[my-folder] =============Importing App================
[my-folder] 
[my-folder] 
[my-folder] [DEBUG] URL parameters API Versionv1
[my-folder] [DEBUG] URL parameters URL https://://***************
[my-folder] [DEBUG] URL parameters Org****
[my-folder] [DEBUG] URL parameters App apiname
[my-folder] [ERROR] Service Account file or bearer token is missing
[my-folder] [ERROR] Service Account file or bearer token is missing
[my-folder] [ERROR] 
[my-folder] 
[my-folder] 
[my-folder] * * * * * * * * * * *
[my-folder] 
[my-folder] This deployment could have failed for a variety of reasons.

I am using below maven command
mvn install -Dapigee.options=override -Dorg=*** -Dusername=**** -Dpassword=**** -Denv=** -Dhosturlversion=v1 -P *** -Dauthtype=basic -X

I am using private cloud version 4.19.06.00 of Apigee.

FYI: seen this issue with version 2.0.1 as well.

Thanks 
Harmeet

**Comment by ssvaidyanathan** [comment]
@harmeetsra - 2.x plugin is for Apigee hybrid. Please use 1.x if you are using the SaaS or Private Cloud version. 2.x is meant for Apigee hybrid. If you are using 1.1.7, thats the latest for SaaS or Private cloud

**Comment by harmeetsra** [comment]
> @harmeetsra - 2.x plugin is for Apigee hybrid. Since you are using the Private Cloud, you can use `1.2.1`. Please use 1.x for Private Cloud (or SaaS).

Thanks @ssvaidyanathan for clarifying this. it would be nice if documentation can be updated so that it won't cause confusion. if it's already there then it may not be very obvious.

**Comment by ssvaidyanathan** [comment]
Its already there.. Please check [this]https://github.com/apigee/apigee-deploy-maven-plugin#note) link
