### ISSUE TITLE
config.json  Token replacements for the tests

### ISSUE THREAD

**Issue by heyitsaakash** [apigee/apigee-deploy-maven-plugin#139]
Hello,

Does config.json only works on the standard policies, proxies and target or is there a way we can trigger the token replacements on the apiproxy/test folders containing integration or unit tests through this file depending on different environment.

thanks,
Aakash

**Comment by ssvaidyanathan** [comment]
@heyitsaakash - it only supports on the apiproxy folder. You can use Maven replacer for your use case. Check [this](https://github.com/apigee/maven-jenkins-ci-demo/blob/master/currency-v1/pom.xml) sample

Am closing this issue as it is not related to the plugin
