### ISSUE TITLE
Profile should not be part of the artifact name or optional

### ISSUE THREAD

**Issue by ruettimac** [apigee/apigee-deploy-maven-plugin#14]
Currently, the artifact name contains the profile name (in this example "test"):

forecastweatherapi1.0-test.zip

But in the case of Release Automation, you will generate a generic artifact which will then be parameterized at deployment time. Artifacts will not be deployed from within maven. If one generated the package without a profile, the name whould be:

forecastweatherapi1.0-null.zip

I propose to not include the profile name if empty or null. This whould enable both options:

a) Deploy into the local dev environment with maven (artifact contains -dev.zip)
b) Create an artifact and store it in the repository for release automation (artifact without profile name)

**Comment by ssvaidyanathan** [comment]
Was fixed in v1.0.5
