### ISSUE TITLE
Support for proxy revision deployment

### ISSUE THREAD

**Issue by ursmalli** [apigee/apigee-deploy-maven-plugin#141]
I would like to deploy an api revision that exist in the proxy xml file.   For example, source code has revision 2 and active revision is 3 , so i would like to deploy the revision that exist in the source code. is there any option to accomplish this?
I tried with update option but it is updating the current  revision 3.
<APIProxy **revision="2**" name="test-api"

Thanks,
Malli

**Comment by ssvaidyanathan** [comment]
@ursmalli - this is not possible. By the way that revision field is something that is added by Apigee when it's deployed. The plugin is not meant for that. You can use the Management API directly to deploy a revision already imported.

**Comment by ursmalli** [comment]
Thank you, Sai.

**Comment by ssvaidyanathan** [comment]
Closing this issue as its not plugin related
