### ISSUE TITLE
Maven Deployment issue with override option.

### ISSUE THREAD

**Issue by chandra7253** [apigee/apigee-deploy-maven-plugin#146]
I have used below command to deploy a proxy.

mvn clean install -Ptest -Dusername=username -Dpassword=password -Doptions=override

The command deploying the new revision to apigee successfully but not clearing the previous revision from UI. Please find attached image for details.

![10240-proxy](https://user-images.githubusercontent.com/71369568/93298804-881dac80-f811-11ea-80c9-dbe3dd80e94c.png)

**Comment by ssvaidyanathan** [comment]
@chandra7253 - will need more info

1. Is this in SaaS or OPDK?
2. Happening consistently only with plugin and not when using UI?
3. Any errors from the maven logs?

**Comment by chandra7253** [comment]
1. it is SaaS
2. Yes its Happening consistently only with plugin and not when using UI.
3. And No errors from maven logs.

**Comment by ssvaidyanathan** [comment]
Can you share the maven stacktrace

**Comment by ssvaidyanathan** [comment]
Closing this issue as there are no activities. If you still face an issue, please re-open this issue
