### ISSUE TITLE
Api proxy deployment error in Hybrid using Deploy maven plugin issue.

### ISSUE THREAD

**Issue by swapna0211950** [apigee/apigee-deploy-maven-plugin#151]
We are implementing CICD for Apigee Hybrid. After the API proxy deployment the plugin is is trying to fetch the deployment status during which it is fetching false as response. Due to this the job is running in loop as plugin is expecting true as the response. Below is the response attached for reference.

Request prepared for the server 
 **************************
GET  https://apigee.googleapis.com/v1/organizations/***************/environments/dev/apis/HealthCheck/revisions/10/deployments
accept: [application/json]
accept-encoding: [gzip]
authorization: [Bearer [Not shown in log]
[DEBUG] returning deployed status: false
[INFO] Getting Deployment Info for Revision: 10
[INFO] Using the service account file to generate a token
[DEBUG] **Access Token** 
[INFO] 

We trriggered management API call to check the deployment status from CLI and we are seeing a proper response. Please let us know how can this issue be fixed.

**Comment by ssvaidyanathan** [comment]
@swapna0211950 - Please redact sensitive info (like tokens) in your posts or comments. 

Which version of the plugin are you using? Can you try with the latest version (v2.0.4) if you are not using it already?

**Comment by ssvaidyanathan** [comment]
Closing this issue. If you still face issue, please re-open
