### ISSUE TITLE
Proxy display name and the description

### ISSUE THREAD

**Issue by rakeshtl** [apigee/apigee-deploy-maven-plugin#16]
Reported by customer:

While deploying the proxy, I can update information in /proxies and /targets directories using config.json file.

Is there any way to update the information in the proxy xml file, such as Proxy name and Description?

It does not seem to be using my proxy xml file.
Here is the file:
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<APIProxy revision="3" name="core_image">
    <ConfigurationVersion minorVersion="0" majorVersion="4"/>
    <CreatedAt>1400771316457</CreatedAt>
    <CreatedBy>mb139h@att.com</CreatedBy>
    <Description>1234</Description>
    <DisplayName>mb139h_core_image</DisplayName>
    <LastModifiedAt>1400771316458</LastModifiedAt>
    <LastModifiedBy>mb139h@att.com</LastModifiedBy>
    <Policies/>
    <ProxyEndpoints>
        <ProxyEndpoint>default</ProxyEndpoint>
    </ProxyEndpoints>
    <Resources/>
    <TargetServers/>
    <TargetEndpoints>
        <TargetEndpoint>default</TargetEndpoint>
    </TargetEndpoints>
    <validate>false</validate>
</APIProxy>

And here is what it creates:

And the more time I re-deploy the code, the longer description becomes. Each time I get a new “::mb139h git revision unknown NJCDTL02MB139H” appended.

I’d like to be able to control the proxy display name and the description.
![image001](https://cloud.githubusercontent.com/assets/2387291/3594697/4eeebbc0-0ca4-11e4-8c46-a064580a9425.png)

**Comment by ssvaidyanathan** [comment]
looks like its not a bug anymore
