### ISSUE TITLE
Add possibility to deploy new revision without undeploying the previous one

### ISSUE THREAD

**Issue by kamnyborg** [apigee/apigee-deploy-maven-plugin#163]
Hi, we have a scenario where we would like to deploy a new revision without undeploying the previous one.

The proxy has the following state before deploy:
Revision 1 contains a deployed v1/someapi

We want to end up with this:
Revision 1 contains a deployed v1/someapi
Revision 2 contains a deployed v2/someapi

It seems like there are no options to support this use case?
Ref https://gitlab.com/samirkantalenka/apigee-deploy-maven-plugin#advanced-configuration-options

Best regards, Kamilla

**Comment by ssvaidyanathan** [comment]
@kamnyborg - I am guessing you are referring to Apigee X/hybrid. If thats the case, it's not possible. Only one proxy revision can be deployed to an environment.

Also I think what you are doing is not best practice. I would suggest you have a proxy per version. For example
Someapi-v1 --> /v1/someapi
Someapi-v2 --> /v2/someapi

With this its separately managed, no confusions around your code base and deployment strategies and also makes it easier for your Product configurations. 

Regarding the options available - please refer to [this](https://github.com/apigee/apigee-deploy-maven-plugin/issues/162) link. The options are `async` and `override` where override is the default option.

**Comment by kamnyborg** [comment]
@ssvaidyanathan Thanks for your quick response, I will discuss the 1 proxy/version solution with my team.
