### ISSUE TITLE
CICD with Actions

### ISSUE THREAD

**Issue by PoomuruganPoopandian** [apigee/apigee-deploy-maven-plugin#164]
Hi,
Do we able to do CICD with the combination of either APIGEE + Actions or APIGEE + Actions + Maven,
I am able to get examples with Jenkins. however there are fewer support towards APIGEE with actions.

Thanks,
Poomurugan

**Comment by ssvaidyanathan** [comment]
@PoomuruganPoopandian - I don't think this is an issue with the plugin. I would recommend you check the [Apigee community](community.apigee.com) as it is meant for such questions.
 
However to answer your question, I can point you to [this](https://github.com/g-lalevee/Apigee-Simple-Github-Pipeline) repo that my colleague wrote which has an example. You can use that as a starting point and modify that to suit your needs. 

I am closing this issue. Any followups, please do them via Apigee community.
