### ISSUE TITLE
"Error fetching Deploymentstatus" error after mvn install -P {{profile}}

### ISSUE THREAD

**Issue by jhd235** [apigee/apigee-deploy-maven-plugin#167]
"Error fetching Deploymentstatus" error after "mvn install -P {{profile}}".
![Screenshot 2021-08-16 073643](https://user-images.githubusercontent.com/5977132/129507879-6d9dcaf0-2766-4d84-b356-964b19f5d0c6.png)

Is this a known issue or maybe a new one? If known, maybe someone could be so kind to point me to the existing description/solution, please?
I've blurred out some NDA info on the screenshot.

could you please let me know if any additional info necessary from my side?

thank you, 
Yermek

**Comment by ssvaidyanathan** [comment]
@jhd235 - This is not a Maven plugin issue. If the `mvn install` run completed successfully, it means it got the success response from the Management plane. It could be possible that the UI is querying the deployment status of a revision that is no longer in the deployed state in an environment. For example, your mvn install could have created a Rev 3 but the UI is looking for the status for rev 2. 

Its not a Maven plugin issue. If you are still seeing this issue, please reach out to Apigee support.

**Comment by jhd235** [comment]
> @jhd235 - This is not a Maven plugin issue. If the `mvn install` run completed successfully, it means it got the success response from the Management plane. It could be possible that the UI is querying the deployment status of a revision that is no longer in the deployed state in an environment. For example, your mvn install could have created a Rev 3 but the UI is looking for the status for rev 2.
> 
> Its not a Maven plugin issue. If you are still seeing this issue, please reach out to Apigee support.

Thank you, @ssvaidyanathan. Hence, I'm closing this issue as answered.
