### ISSUE TITLE
apigee-deploy-maven-plugin: How to create "Environments>Target servers" in Apigee Hybrid?

### ISSUE THREAD

**Issue by jhd235** [apigee/apigee-deploy-maven-plugin#168]
https://www.googlecloudcommunity.com/gc/Apigee/apigee-deploy-maven-plugin-How-to-create-quot-Environments-gt/m-p/167454/highlight/true#M67116

apigee-deploy-maven-plugin: How to create "Environments>Target servers" in Apigee Hybrid?
I'm currently trying to use https://github.com/apigee/apigee-deploy-maven-plugin/tree/hybrid
to create "Environments>Target servers" in Apigee Hybrid. However, no results - no targets created after running plugin.

Could someone please be so kind to suggest to me the correct ways of making such a task?

I utilize for this task config.json:
`{
    "configurations": [
        {
            "name": "sandbox",
            "targets": [
                {
                  "name": "promotion.xml","tokens": [
                    {
                      "xpath": "/TargetEndpoint/HTTPTargetConnection/LoadBalancer/Algorithm","value": "RoundRobin"},{
                      "xpath": "/TargetEndpoint/HTTPTargetConnection/LoadBalancer/Server[1]/@name","value": "s1"},{
                      "xpath": "/TargetEndpoint/HTTPTargetConnection/LoadBalancer/Server[2]/@name","value": "s2"},{
                      "xpath": "/TargetEndpoint/HTTPTargetConnection/LoadBalancer/Server[3]/@name","value": "s3"},{
                      "xpath": "/TargetEndpoint/HTTPTargetConnection/LoadBalancer/MaxFailures","value": "10"},{
                      "xpath": "/TargetEndpoint/HTTPTargetConnection/LoadBalancer/RetryEnabled","value": "true"}
                  ]
                }              
              ]
        }]}
`

Good day, dear community,
thank you, 

best regards, Yermek

**Comment by ssvaidyanathan** [comment]
Hi @jhd235 - you need to use the [Apigee Maven Config plugin](https://github.com/apigee/apigee-config-maven-plugin/tree/hybrid/samples).

**Comment by ssvaidyanathan** [comment]
Since this is not deploy plugin related, am closing this issue
