### ISSUE TITLE
Change the update implementation of the plugin to use alternate set of API calls for deployment of proxy

### ISSUE THREAD

**Issue by sriki77** [apigee/apigee-deploy-maven-plugin#17]
The current API call used to update a given version of the proxy is the following.

`POST  https://api.enterprise.apigee.com/v1/organizations/<org name>/apis?action=import&name=<apiproxy name>&validate=true`

This API is a heavy weight call that results in timeout on Edge.  We need to change the implementation to use alternate set of API calls (split the single call) to achieve the same result. These API calls should undeploy,update and deploy the new version of the code.

**Comment by bialesdaniel** [comment]
It would nice if we could do zero downtime deploys using the update option. I would like to do a deploy without creating a new revision

**Comment by ssvaidyanathan** [comment]
update option is implemented and available. 
Closing this issue
