### ISSUE TITLE
access token not valid

### ISSUE THREAD

**Issue by Feroz1991** [apigee/apigee-deploy-maven-plugin#171]
i am getting access token not valid error while i can use the same bearer token and deploy from my local. but from jenkins its rying through maven its not working

**Comment by ssvaidyanathan** [comment]
@Feroz1991 - pls make sure that the JWT you are passing matches the client_id and email you have in your pom

When you are passing a bearer token, make sure the Apigee Maven profile you are calling is also having <apigee.clientid> and <apigee.username>. The plugin verifies the JWT against those and checks it they match. If they don't then it throws the Invalid Access Token error

**Comment by anoopsaxena** [comment]
We are also getting the error **Access token not valid**
However We can able to upload ( Only upload not deployed ) with the same bearer token in apigee env from local command prompt through maven command.
From Jenkins pipeline its not working. is <apigee.clientid> same as apigee.user ? it's blocekr for me,  Kindly help me to resolve this error. Thanks

**Comment by ssvaidyanathan** [comment]
@anoopsaxena - not sure I am following what you mean.

Access token not valid could have three possible things
1) its not a valid token
2) the client id you are passing does not match with the value in the JWT
3) the username you are passing does not match with the value in the JWT

The URL configured incorrectly has nothing to do with the plugin issue.

**Comment by ssvaidyanathan** [comment]
@Feroz1991 - Can you please confirm if you still see the issue? If not, I would like to close the issue

**Comment by shaunmirza** [comment]
I am also experiencing the same issue. Apigee org is SSO enabled with external IDP. I am using the following command in my Jenkinsfile to deploy my proxy:
 
mvn -B install -P<<{ENVIRONMENT}>> -Dusername=<<{APIGEE_USERNAME}>> -Dorg=<<{ORG}>> -Dauthtype=oauth -Dbearer=<<{ACCESS_TOKEN}>> -DartifactName=<<{apiproxyName}>> -DapiType=apiproxy
 
The <apigee.clientid> and <apigee.username> are provided in the sharedpom.xml. The error returned in the logs goes as follows:
 
Failed to execute goal io.apigee.build-tools.enterprise4g:apigee-edge-maven-plugin:1.2.2:deploy (deploy-bundle) on project SampleDeploy1: Access token not valid -> [Help 1]

**Comment by ssvaidyanathan** [comment]
@shaunmirza - Can you please decode your bearer token (using jwt.io) and see if the apigee.clientid matches from the value in the token and also the same for apigee.username. If they dont match, the plugin will raise "Access token not valid". 

Also please check if the token is not expired.

**Comment by ssvaidyanathan** [comment]
@shaunmirza - any update on this? Else I will have to close this issue

**Comment by shaunmirza** [comment]
> @shaunmirza - any update on this? Else I will have to close this issue

Clientid and username matched the token. The culprit was the tokenurl in the profile of the sharedpom.xml. I had to change it to my custom url. Thanks!
