### ISSUE TITLE
proxy settings allow https-only protocol support

### ISSUE THREAD

**Issue by yuriylesyuk** [apigee/apigee-deploy-maven-plugin#178]
As per https://github.com/apigee/apigee-deploy-maven-plugin#to-configure-a-proxy, "only  https protocol is supported". 

My case is an enterprise proxy with authentication that is only http. 

When trying to use a plugin and proxy configuration in ~/.m2 config file, the plugin causes timeout that ends with 400.

Is there any way to add an http protocol proxy support?

Thank you

**Comment by ssvaidyanathan** [comment]
@yuriylesyuk - I have pushed a fix for this in a separate branch ([Issue178](https://github.com/apigee/apigee-deploy-maven-plugin/tree/Issue178)). Before I merge and release, can you test it for me please

Steps:
1. Proxy settings in your `~/.m2/settings.xml` file
2. Clone the repo and switch to Issue178 branch
2. Execute `mvn install` on the main project to create a 2.3.0-SNAPSHOT on your local .m2/repository
3. Update the `samples/mockapi-recommended/src/gateway/shared-pom.xml` to use `2.3.0-SNAPSHOT` version (Line number 76)
4. `cd samples/mockapi-recommended/src/gateway/Mock-v1`
5. Run `mvn clean install -Ptest -Dorg=$ORG -Denv=$ENV -Dbearer=$(gcloud auth print-access-token)`

Let me know if it works with the proxy settings and report back if you see any issues

**Comment by ssvaidyanathan** [comment]
Fixed in v2.3.0
