### ISSUE TITLE
config.json replacement code depends on <proxy>.xml/description file to be present

### ISSUE THREAD

**Issue by vitor-a-pinto** [apigee/apigee-deploy-maven-plugin#184]
Without a config.json maven can deploy a proxy without the  <proxy>.xml be present, but with config.json there, it fails with 

`Failed to execute goal io.apigee.build-tools.enterprise4g:apigee-edge-maven-plugin:2.3.0:configure (configure-bundle) on project HelloWorld2: Index: 0, Size: 0 -> [Help 1]`

- Apigee X
- Plugin version 2.3.0

Attached proxy bundle for reproducing (without <proxy>.xml file):
[apiproxies.zip](https://github.com/apigee/apigee-deploy-maven-plugin/files/8409317/apiproxies.zip)
 
If I add xml below to HelloWorld2\apiproxy dir configure-bundle task completes  just fine
[HelloWorld2.zip](https://github.com/apigee/apigee-deploy-maven-plugin/files/8409325/HelloWorld2.zip)

**Comment by ssvaidyanathan** [comment]
Fixed and released in v2.3.1

Please test and let me know if its working as expected. You can re-open the issue if the issue still persists

**Comment by vitor-a-pinto** [comment]
I confirm it is solved. Thanks for the quick fix!
