### ISSUE TITLE
Dependency exception during configure-bundle goal

### ISSUE THREAD

**Issue by PG9999** [apigee/apigee-deploy-maven-plugin#194]
Hi, We have been facing an error in our pipeline. Similar issue logged here #184 

`Failed to execute goal io.apigee.build-tools.enterprise4g:apigee-edge-maven-plugin:1.3.2:configure (configure-bundle) on project Biller-Payment-v2: Execution configure-bundle of goal io.apigee.build-tools.enterprise4g:apigee-edge-maven-plugin:1.3.2:configure failed: Plugin io.apigee.build-tools.enterprise4g:apigee-edge-maven-plugin:1.3.2 or one of its dependencies could not be resolved: Failed to collect dependencies at io.apigee.build-tools.enterprise4g:apigee-edge-maven-plugin:jar:1.3.2 -> com.google.guava:guava:jar:31.1.0.redhat-00001: Failed to read artifact descriptor for com.google.guava:guava:jar:31.1.0.redhat-00001: com.google.guava:guava-parent:pom:31.1.0.redhat-00001 was not found in`

Product - Apigee OPDK 4.50.00.14
Version - 1.3.2

Just wondering if the same needs to be fixed in plugin 1.x version

**Comment by ssvaidyanathan** [comment]
@PG9999 - Are you pointing your pom to the repo1.maven.org repository or your corporate Maven repo? If latter, can you check if that repo has the dependency in it?

**Comment by ssvaidyanathan** [comment]
not sure where that dependency is coming from, will have to find that. Are you still having issues?

**Comment by PG9999** [comment]
@ssvaidyanathan The dependency is coming from below guava maven dependency. 
`			<dependency>
				<groupId>com.google.guava</groupId>
				<artifactId>guava</artifactId>
				<version>[24.1.1,)</version>
			</dependency>`
Refer - [https://github.com/apigee/apigee-deploy-maven-plugin/blob/master/pom.xml](pom)

Where the version mentioned is [24.1.1,) that means **latest available version** above 24.1.1. 

So while building, maven is trying to fetch the latest version that is [https://mvnrepository.com/artifact/com.google.guava/guava/31.1.0.redhat-00001](url) released recently on Jul 07, 2022. 

The issue here is that we are using internal maven repository which probably has taken time to sync with maven central repo or could be some other reason. I will talk to the concern team here but meanwhile do we know if there is a way to override it? or any other workaround? Thanks.

**Comment by PG9999** [comment]
Update - I am able to fix it, but it's a workaround. 
I have added dependency under the plugin to override it in my parent POM. Have a look below.  

`<plugin>
                <groupId>io.apigee.build-tools.enterprise4g</groupId>
                <artifactId>apigee-edge-maven-plugin</artifactId>
                <version>1.3.2</version>
                <dependencies>
                    <dependency>
                        <groupId>com.google.guava</groupId>
                        <artifactId>guava</artifactId>
                        <version>30.1.0.redhat-00001</version>
                    </dependency>
                </dependencies>
                <executions>
                    <execution>
                        <id>configure-bundle</id>
                        <phase>package</phase>
                        <goals>
                            <goal>configure</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>deploy-bundle</id>
                        <phase>install</phase>
                        <goals>
                            <goal>deploy</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>`

However, It's a temporary fix and good to have a permanent solution as it might happen again. I would propose having an exact version of guava in place of looking for a latest version as it might happen again.

**Comment by ssvaidyanathan** [comment]
@PG9999 - will probably find if guava is needed by the plugin and if not, remove it from the pom and release a new version

**Comment by ssvaidyanathan** [comment]
I've removed the guava references in the pom and released a new version v1.3.3
It should be available in a few hours. Please try the new version and let me know. Will close the issue after that
