### ISSUE TITLE
Not able to deploy apiproxy

### ISSUE THREAD

**Issue by konthamvivek** [apigee/apigee-deploy-maven-plugin#197]
i want to deploy apiproxy using deploy plugin but unable to deploy as i was not allowed to connect apigee.google.com from my private server.
![image](https://user-images.githubusercontent.com/90710169/192145783-b7074bad-eee2-4cc1-8e9e-8d326984312e.png)

to connect to the host url we had to connect to a proxy and do deployments using deploy maven plugin i had used below command but it is not working properly .
"mvn -X package -Dhttp.proxyHost=127.0.0.1 -Dhttp.proxyPort=8080 -Dhttps.proxyHost=127.0.0.1 -Dhttps.proxyPort=8080 apigee-enterprise:deploy -Phybrid-apiproxy -Dorg=org -Denv=env} -Dfile=file 

how to connect to proxy host url and deploy proxy using deploy plugin ?

**Comment by ssvaidyanathan** [comment]
Hi @konthamvivek - pls follow the steps provided [here](https://github.com/apigee/apigee-deploy-maven-plugin/tree/hybrid#to-configure-a-proxy)

Hope you are using a version > v2.3.0

**Comment by ssvaidyanathan** [comment]
@konthamvivek - did you try? Can I mark this issue as closed?

**Comment by ssvaidyanathan** [comment]
Thanks for closing. Did you get it to work? Appreciate if you can share
