### ISSUE TITLE
Undeploying apiproxy

### ISSUE THREAD

**Issue by konthamvivek** [apigee/apigee-deploy-maven-plugin#198]
while trying to undeploy apiproxy using below command in apigeeX/hybrid

**mvn clean install apigee-enterprise:deploy -Phybrid-apiproxy -Dorg=$org -Denv=$env -Dbearer=$token**

we are able to undeploy but the proxy is getting deleted entirely , **we just only want to undeploy the deployed revision for respected api/sharedflow**.

apigee hybrid/X deploy plugin version :2.1.0

below are added in profile of apiproxy in pom.xml

<apigee.options>clean</apigee.options>
<apigee.override.delay>5</apigee.override.delay>

**Comment by ssvaidyanathan** [comment]
As documented in the README - https://github.com/apigee/apigee-deploy-maven-plugin/tree/hybrid#to-delete-the-proxy-or-sharedflow-v203-or-later

The `clean` option is working as expected. Its meant to delete the proxy

The plugin today does not support just "undeploy" and never did

**Comment by konthamvivek** [comment]
can we expect these feature in next upcoming version ?

**Comment by ssvaidyanathan** [comment]
No - there is no plan.
Why do you need it?

**Comment by ssvaidyanathan** [comment]
Closing as there are not details
