### ISSUE TITLE
Apigee Network call error

### ISSUE THREAD

**Issue by srinivasmurari** [apigee/apigee-deploy-maven-plugin#200]
hi, 
when we tried to deploy API proxies using the cicd pipeline we are not able to deploy and got **Apigee Network to call error and connection timed out issue**,we need to connect via proxy to do any deployments from cicd server we had added proxy in our seetings.xml file and using 2.3.0 maven deploy plugin.

we have tested sample management APIs using bearer token we can make post & get from the same cicd server, but using the plugin we are getting the below-attached issue
**deploy command used**
****mvn clean install -phybrid-apiproxy -Dorg=orgname -Denv=envname -Dbearer=token****

![Screenshot 2022-11-01 195413](https://user-images.githubusercontent.com/108681311/199257194-f119bb90-a40c-488a-b618-a304332a4466.png)

**Comment by ssvaidyanathan** [comment]
@srinivasmurari - you have created the issue in the wrong repo. Please open [here](https://github.com/apigee/apigee-config-maven-plugin/issues/new)
I am closing this issue
