### ISSUE TITLE
Error when specifying <apigee.options>

### ISSUE THREAD

**Issue by andythehood** [apigee/apigee-deploy-maven-plugin#203]
I'm getting errors when configuring various <apigee.options> in my pom.xml with 2.3.5

For example, specifying <apigee.options>validate</apigee.options> results in this error:

> [ERROR] Failed to execute goal io.apigee.build-tools.enterprise4g:apigee-edge-maven-plugin:2.3.5:deploy (deploy-bundle-step) on project currency-v1: MojoExecutionException: No enum constant io.apigee.buildTools.enterprise4g.mavenplugin.DeployMojo.OPTIONS.validate -> [Help 1]

Similarly for <apigee.options>update</apigee.options>:

> [ERROR] Failed to execute goal io.apigee.build-tools.enterprise4g:apigee-edge-maven-plugin:2.3.5:deploy (deploy-bundle-step) on project currency-v1: MojoExecutionException: No enum constant io.apigee.buildTools.enterprise4g.mavenplugin.DeployMojo.OPTIONS.update -> [Help 1]

Also, while <apigee.options>override</apigee.options> works, <apigee.override.delay> doesn't:

> [ERROR] Failed to execute goal io.apigee.build-tools.enterprise4g:apigee-edge-maven-plugin:2.3.5:deploy (deploy-bundle-step) on project currency-v1: MojoExecutionException: com.google.api.client.http.HttpResponseException: 400 Bad Request
> [ERROR] {
> [ERROR] "error": {
> [ERROR] "code": 400,
> [ERROR] "message": "Invalid JSON payload received. Unknown name \"delay\": Cannot bind query parameter. Field 'delay' could not be found in request message.",
> [ERROR] "status": "INVALID_ARGUMENT",
> [ERROR] "details": [
> [ERROR] {
> [ERROR] "@type": "type.googleapis.com/google.rpc.BadRequest",
> [ERROR] "fieldViolations": [
> [ERROR] {
> [ERROR] "description": "Invalid JSON payload received. Unknown name \"delay\": Cannot bind query parameter. Field 'delay' could not be found in request message."
> [ERROR] }
> [ERROR] ]
> [ERROR] }
> [ERROR] ]
> [ERROR] }
> [ERROR] }
> [ERROR] -> [Help 1]

[pom.xml.txt](https://github.com/apigee/apigee-deploy-maven-plugin/files/10718451/pom.xml.txt)

**Comment by ssvaidyanathan** [comment]
@andythehood - Please refer to [this README](https://github.com/apigee/apigee-deploy-maven-plugin/tree/hybrid) for Apigee X/hybrid versions. You were probably looking at the Edge/OPDK README that supports options like validate and update. Version 2.x of the plugin does not support those options.

Same applies for apigee.override.delay. Check [this](https://cloud.google.com/apigee/docs/reference/apis/apigee/rest/v1/organizations.environments.apis.revisions.deployments/deploy) doc

**Comment by andythehood** [comment]
Thanks Sai. Yes, I had copied the pom from an older Edge project, and was refering to the [Readme](https://github.com/apigee/apigee-deploy-maven-plugin/blob/master/README.md) from the default master branch.

But I've now noticed the Note in it that says to use the hybrid branch for the 2.x version for X/Hybrid.

**Comment by ssvaidyanathan** [comment]
Perfect! Ok to close this issue?

**Comment by andythehood** [comment]
Sure, good with me.

Although it does seem a little odd to me that the default branch is still for the older Edge/OPDK version and you have to switch to a branch named 'hybrid' for the current ApigeeX version.

**Comment by ssvaidyanathan** [comment]
great point @andythehood 

I have updated the default branch to be "main" and its pointing to the Apigee X/hybrid version

The Edge/OPDK version is on a branch name "1.x"
