### ISSUE TITLE
New "Promote" goal: deploy existing proxy revision to another environment 

### ISSUE THREAD

**Issue by g-lalevee** [apigee/apigee-deploy-maven-plugin#204]
To be able to keep the same revision number across several environment, it could be useful to be able to redeploy a proxy revision to another environment without having to rebuild it (and Apigee X creates a new revision number for each build...)

**Scenario**:

1- build proxy and deploy it to dev environment
`mvn install  -Dorg=MyOrg -Denv=MyEnv ...`

2- when proxy ok, promote a development revision to test environment. Options:
   - choose a version number to be deployed into target environment (if revision doesn't exist, error)
        `mvn promote -Dorg=MyOrg -Denv=TargetEnv -Drevision=23 ...`
   - choose the latest existing revision in the organization to be deployed into target environment
        `mvn promote -Dorg=MyOrg -Denv=TargetEnv  ...`
   - choose the latest revision deployed in a given environment to be deployed into target environment
        `mvn promote -Dorg=MyOrg -Dsource=SourceEnv -Denv=TargetEnv  ...`

**Comment by g-lalevee** [comment]
Addendum: promote goal should work with both Proxy and Shareflow

**Comment by ssvaidyanathan** [comment]
@g-lalevee - what if for 

- choose the latest revision deployed in a given environment to be deployed into target environment
`mvn promote -Dorg=MyOrg -Dsource=SourceEnv -Denv=TargetEnv  ...`

there are no revisions deployed in the sourceEnv? do we pick the latest revision in the org and deploy that or throw an error? I prefer throwing an error. But wanted to check with you
