### ISSUE TITLE
How to define override true in maven plugin for deploying proxy

### ISSUE THREAD

**Issue by satishbkodali** [apigee/apigee-deploy-maven-plugin#205]
Currently we are using the apigee edge SAAS deployments using maven plugin

`mvn install -P ${env} -Dusername=${username} -Dauthtype=oauth -Dbearer=${authToken} -Dapigee.config.options=update`

I see curl commands for seamless deployments as
https://docs.apigee.com/api-platform/deploy/deploy-api-proxies-using-management-api#seamless

How to do this seamless in mvn plugin so that there wont be any downtime during deployment

@ssvaidyanathan

**Comment by ssvaidyanathan** [comment]
@satishbkodali - the "override" option supports what you are asking

https://github.com/apigee/apigee-deploy-maven-plugin/tree/1.x#note-3 has more info

Since this is something thats supported, I am closing this issue. If otherwise, please do reopen

**Comment by satishbkodali** [comment]
@ssvaidyanathan looks like it is not accepting override
as -Dapigee.config.options is using the parameters from https://github.com/apigee/apigee-config-maven-plugin
So how to make this work

**Comment by ssvaidyanathan** [comment]
You r confusing two different plugins
Config plugin is for Apigee configurations
IF you want seamless deployments, you need to use 
```xml
<apigee.options>override</apigee.options>
```
you can parameterize this or set this in your Maven profile

**Comment by satishbkodali** [comment]
can i parameterize both like this

mvn install -P ${env} -Dusername=${username} -Dauthtype=oauth -Dbearer=${authToken} -Dapigee.config.options=update -Doptions=override?

**Comment by ssvaidyanathan** [comment]
yes.. check https://github.com/apigee/apigee-deploy-maven-plugin/blob/d19b343e2a1c55fd2b25c11cafbd2ffe115224ea/samples/mockapi-recommended/src/gateway/shared-pom.xml#L110

**Comment by satishbkodali** [comment]
Thanks
