### ISSUE TITLE
v1.3.3 how to remove profile name from artifact name

### ISSUE THREAD

**Issue by dhanushyaselva** [apigee/apigee-deploy-maven-plugin#209]
When i try to deploy artifact by placing it in target folder using the plugin, i get this error.

[INFO] Scanning for projects...
[INFO]
[INFO] ----------< com.****.api:test-merchant-experience-api-v1 >----------
[INFO] Building test-merchant-experience-api-v1 1.0.7-SNAPSHOT
[INFO]   from pom.xml
[INFO] --------------------------------[ pom ]---------------------------------
[INFO]
[INFO] --- apigee-enterprise:1.2.2:deploy (default-cli) @ test-merchant-experience-api-v1 ---
[INFO] Request prepared for the server
 **************************
GET  https://api.enterprise.apigee.com/v1/organizations/*******/apis/test-merchant-experience-api-v1/deployments/
accept: [application/json]
accept-encoding: [gzip]
authorization: [Basic [Not shown in log]
[ERROR] 404 Not Found
{
  "code" : "messaging.config.beans.ApplicationDoesNotExist",
  "message" : "APIProxy named test-merchant-experience-api-v1 does not exist in organization *******",
  "contexts" : [ ]
}
[INFO] Updating apiproxy/test-merchant-experience-api-v1 revision 1 (current active revision is -1)
[INFO] Request prepared for the server
 **************************
POST  https://api.enterprise.apigee.com/v1/organizations/*******/apis/test-merchant-experience-api-v1/revisions/1
accept: [application/json]
accept-encoding: [gzip]
authorization: [Basic [Not shown in log]
content-type: application/octet-stream
 [Request body contains data, not shown]

[ERROR] 404 Not Found
{
  "code" : "beans.BeanDoesNotExist",
  "message" : "ApplicationBean : test-merchant-experience-api-v1 does not exist",
  "contexts" : [ ]
}
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  2.026 s
[INFO] Finished at: 2023-04-03T10:21:27+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.apigee.build-tools.enterprise4g:apigee-edge-maven-plugin:1.2.2:deploy (default-cli) on project test-merchant-experience-api-v1: 404 Not Found
[ERROR] {
[ERROR]   "code" : "beans.BeanDoesNotExist",
[ERROR]   "message" : "ApplicationBean : test-merchant-experience-api-v1 does not exist",
[ERROR]   "contexts" : [ ]
[ERROR] }
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

This is the first revision of the proxy.

the maven command i use is:
mvn apigee-enterprise:deploy -P dev

my pom has this sections:

	<artifactId>apigee-edge-maven-plugin</artifactId>
	<version>1.3.3</version>
	<executions>
		<execution>
			<id>configure-bundle</id>
			<phase>package</phase>
			<goals>
				<goal>configure</goal>
			</goals>
		</execution>
		<execution>
			<id>deploy-bundle</id>
			<phase>install</phase>
			<goals>
				<goal>deploy</goal>
			</goals>
		</execution> 
	</executions>

*
*
**
*
*
	<profiles>
		<profile>
			<id>dev</id>
			<properties>
				<apigee.profile>dev</apigee.profile>
				<apigee.env>dev</apigee.env>
				<apigee.hosturl>https://api.enterprise.apigee.com</apigee.hosturl>
				<apigee.apiversion>v1</apigee.apiversion>
				<apigee.org>***********</apigee.org>
				<apigee.revision>1</apigee.revision>
				<apigee.username>**************</apigee.username>
				<apigee.password>*************</apigee.password>
				<apigee.options>update</apigee.options>
			</properties>
		</profile>

**Comment by ssvaidyanathan** [comment]
@dhanushyaselva - you will need to execute `apigee-enterprise:configure` before `apigee-enterprise:deploy`. The `apigee-enterprise:configure` creates the Apigee proxy bundle (zip in your target directory) and then `apigee-enterprise:deploy` picks that up and deploys it. In your case, since you are not calling configure, the zip is not in your target directory. Hence the deployment is failing.

**Comment by dhanushyaselva** [comment]
Hi @ssvaidyanathan thanks for the response. 

Actually, I created a deployment pipeline in jenkins and i wanted to leverage the plugin to deploy the artifact only. i have a separate plugin for builds. but, i was able to solve the above issue, after removing <apigee.revision>1</apigee.revision> from my pom. looks like <apigee.revision> should be used only in combination with  <apigee.option> as override. 

I also updated my version to 1.3.3. but the problem i am facing with this version is that the artifact created during build is appending environment name. <projectname><version><profile name>.zip


@ssvaidyanathan  is there a way to remove <profile name> from artifact name ?

**Comment by ssvaidyanathan** [comment]
Yes - pls do not include the <apigee.revision>
The plugin is meant to package and deploy from your repo. 


Regarding the artifact name - can you confirm what you have in your pom. It uses the name you have configured for `artifact` in your pom.xml. Change that it should fix the issue

**Comment by dhanushyaselva** [comment]
Thanks for getting back quickly @ssvaidyanathan 
Below is my pom

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<groupId>com.openedge.api</groupId>
	<artifactId>test-api-v1</artifactId>
	<version>1.0.19-SNAPSHOT</version>
	<name>test-merchant-experience-api-v1</name>
	<packaging>pom</packaging>
	<modelVersion>4.0.0</modelVersion>
	<parent> 
		<groupId>com.openedge.api</groupId>
		<artifactId>parent-pom</artifactId>
		<version>1.0.0</version>
		<relativePath>../parent-pom/pom.xml</relativePath>
	</parent>
	<scm>
		<connection>scm:git:https://${bitbucket.domain}/bitbucket/scm/apip/${project.artifactId}-v1.git</connection>
		<developerConnection>scm:git:https://${bitbucket.domain}/bitbucket/scm/apip/${project.artifactId}.git</developerConnection>
		<url>https://${bitbucket.domain}/bitbucket/scm/apip/${project.artifactId}.git</url> 
	  <tag>HEAD</tag>
  </scm>
	<distributionManagement>
		<repository>
			<id>releases</id>
			<url>http://**/artifactory/libs-release-local/</url>
		</repository>
		<snapshotRepository>
			<id>snapshots</id>
			<url>http://***/artifactory/libs-snapshot-local/</url>
		</snapshotRepository>
 </distributionManagement>
</project>


<?xml version="1.0"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>com.openedge.api</groupId>
	<artifactId>parent-pom</artifactId>
	<packaging>pom</packaging>
	<version>1.0.0</version>
	<modules>
		<module>../apigee-artifact</module>
	</modules>
	<build>
		<plugins>
			<plugin>
              
				<artifactId>maven-clean-plugin</artifactId>
				<version>2.5</version>
			</plugin>
            <plugin>
				<groupId>com.cj.jshintmojo</groupId>
				<artifactId>jshint-maven-plugin</artifactId>
				<version>1.6.0</version>
				<executions>
					<execution>
					<id>jslint</id>
					<phase>package</phase>
					<goals>
					<goal>lint</goal>
					</goals>
				</execution>
				</executions>
				<configuration>  
					<directories>
						<directory>../apigee-artifact/apiproxy/resources/jsc</directory>
						
						</directories>
					<excludes>
					<exclude>node/node_modules</exclude>
						</excludes>
					<reporter>html</reporter>
					<reportFile>lintReport.html</reportFile>
				</configuration>
			</plugin>  
			<plugin>
				<artifactId>maven-resources-plugin</artifactId>
				<version>2.6</version>
				<executions>
					<execution>
						<id>copy-resources</id>
						<phase>prepare-package</phase>
						<goals>
							<goal>copy-resources</goal>
						</goals>
						<configuration>
							<overwrite>true</overwrite>
							<outputDirectory>${basedir}/target/apiproxy</outputDirectory>
							<resources>
								<resource>
									<directory>apiproxy</directory>
								</resource>
							</resources>
						</configuration>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>com.google.code.maven-replacer-plugin</groupId>
				<artifactId>replacer</artifactId>
				<version>1.5.3</version>
				<executions>
					<execution>
                        <id>Add Deployment Suffix to Base Path</id>
						<phase>prepare-package</phase>
						<goals>
							<goal>replace</goal>
						</goals>
                          <configuration>
                            <basedir>${project.build.directory}/apiproxy/proxies/</basedir>
                            <includes>
                                <include>*.xml</include>
                            </includes>
                            <replacements>
                                <replacement>
                                    <token>${basepath}</token>
                                    <value>${basepath}${deploymentpath.delimiter}${deployment.suffix}</value>
                                </replacement>
                            </replacements>
                        </configuration>
					</execution>
                 	<execution>
						<id>Replace-Description</id>
						<phase>prepare-package</phase>
						<goals>
							<goal>replace</goal>
						</goals>
						<configuration>
							<basedir>${project.build.directory}/apiproxy</basedir>
							<includes>
								<include>*.xml</include>
							</includes>
							<replacements>
								<replacement>
									<xpath>/APIProxy/Description/text()</xpath>
									<token>Release-Version:(\b\d{1,2}\.\d{1,2}\.\d{1,5}\b)</token>
									<value>Release-Version:${deployment.version}</value>
								</replacement>
							</replacements>
						</configuration>	
					</execution>			 
				</executions>
			</plugin>
			<plugin>
				<groupId>io.apigee.build-tools.enterprise4g</groupId>
				<artifactId>apigee-edge-maven-plugin</artifactId>
				<version>1.3.3</version>
				<executions>
					<execution>
						<id>configure-bundle</id>
						<phase>package</phase>
						<goals>
							<goal>configure</goal>
						</goals>
					</execution>
                  	<execution>
						<id>deploy-bundle</id>
						<phase>install</phase>
						<goals>
							<goal>deploy</goal>
						</goals>
					</execution> 
				</executions>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-release-plugin</artifactId>
				<version>2.5.3</version>
				<configuration>
					<checkModificationExcludes>
						<checkModificationExclude>src/gateway/apigee-artifact/build.sh</checkModificationExclude>
					</checkModificationExcludes>
				</configuration>			
			</plugin>
		</plugins>
	</build>
	<properties>
        <deployment.delimiter>-</deployment.delimiter>
		<deployment.suffix>${user.name}</deployment.suffix>
        <deployment.version>${project.version}</deployment.version>
		<main.basedir>${project.basedir}</main.basedir>
		<groovy.version>2.5.14</groovy.version>
		<sonar.host.url>http://localhost:9000</sonar.host.url>
		<systemProp.sonar.host.url>http://localhost:9000</systemProp.sonar.host.url>
		<sonar.login>place_holder_sonar_token_value</sonar.login>
		<sonar.projectName>test-api-v1</sonar.projectName>
		<sonar.projectKey>test-merchant-experience-api-v1</sonar.projectKey>
		<sonar.exclusions>**/jenkins/**,**/helm/**"</sonar.exclusions>
		<sonar.dynamicAnalysis>reuseReports</sonar.dynamicAnalysis>
		<sonar.sources>./apiproxy</sonar.sources>
		<sonar.sourceEncoding>UTF-8</sonar.sourceEncoding>
		<sonar.branch.name>${branchName}</sonar.branch.name>
		<sonar.scm.disabled>true</sonar.scm.disabled>		
	</properties>
	
	<profiles>
		<profile>
			<id>dev</id>
			<properties>
				<apigee.profile>dev</apigee.profile>
				<apigee.env>dev</apigee.env>
				<apigee.hosturl>https://api.enterprise.apigee.com</apigee.hosturl>
				<apigee.apiversion>v1</apigee.apiversion>
				<apigee.org>openedgedev</apigee.org>
				
				<apigee.username>${username}</apigee.username>
				<apigee.password>${password}</apigee.password>
				<apigee.options>override,update</apigee.options>
			</properties>
		</profile>
		<profile>
			<id>sandbox</id>
			<properties>
				<apigee.profile>sandbox</apigee.profile>
				<apigee.env>sandbox</apigee.env>
				<apigee.hosturl>https://api.enterprise.apigee.com</apigee.hosturl>
				<apigee.apiversion>v1</apigee.apiversion>
				<apigee.org>openedge</apigee.org>
				
				<apigee.username>${username}</apigee.username>
				<apigee.password>${password}</apigee.password>
				<apigee.options>override,update</apigee.options>
			</properties>
		</profile>
		<profile>
			<id>test</id>
			<properties>
				<apigee.profile>test</apigee.profile>
				<apigee.env>test</apigee.env>
				<apigee.hosturl>https://api.enterprise.apigee.com</apigee.hosturl>
				<apigee.apiversion>v1</apigee.apiversion>
				<apigee.org>openedge</apigee.org>
				
				<apigee.username>${username}</apigee.username>
				<apigee.password>${password}</apigee.password>
				<apigee.options>override,update</apigee.options>
			</properties>
		</profile>				
	</profiles>
</project>

**Comment by dhanushyaselva** [comment]
the maven build command  used is 
mvn -f pom.xml package -Pdev -Ddeployment.suffix= -Ddeploymentpath.delimiter=/ -Ddeployment.delimiter=- -Dbasepath=$APIGEE_API_BASE_PATH -Dapigee.host=$APIGEE_MGMT_API_HOST -Dusername=$APIGEE_CREDS_USR -Dpassword=$APIGEE_CREDS_PSW -Dorg=**** sonar:sonar -Dsonar.login=$sonar_login_token -Dsonar.branch.name=$branch_name


the artifactname created is test-api-v1-1.0.19-SNAPSHOT-dev.zip

**Comment by dhanushyaselva** [comment]
@ssvaidyanathan Thanks, point noted about the apigee.options.
the development team is not satisfied with the naming convention as this will be the artifact deployed to PIT and higher environments. they think this might be deceiving

**Comment by dhanushyaselva** [comment]
@ssvaidyanathan also version 1.1.6 did not have this issue.

https://github.com/apigee/apigee-deploy-maven-plugin/pull/86 this change was added to address the above issue right ?

**Comment by ssvaidyanathan** [comment]
Unfortunately its built into the plugin 
https://github.com/apigee/apigee-deploy-maven-plugin/blob/d19b343e2a1c55fd2b25c11cafbd2ffe115224ea/src/main/java/io/apigee/buildTools/enterprise4g/mavenplugin/GatewayAbstractMojo.java#L454

This is what added as part of another issue that was opened. 

Can you have a step added in your Jenkins file to rename that zip after the "package" command?

**Comment by dhanushyaselva** [comment]
Thanks @ssvaidyanathan yes, i will try doing that

**Comment by dhanushyaselva** [comment]
@ssvaidyanathan thanks for that suggestion. it worked

**Comment by dhanushyaselva** [comment]
@ssvaidyanathan can you suggest the apigee.options to use based on my use case below ?

so, I have a separate CD pipeline where I download artifact from artifactory and deploy to apigee env using apigee deploy maven plugin. Basically, I want to deploy these artifacts with newer increemented revisions and if its the same artifact trying to be deployed again I dont want the current revision to be increemented, but to update in the same revision. I tried "update" option,, but it does not seem to satisfy this.

**Comment by ssvaidyanathan** [comment]
can you explain the complete process.. Wondering why are you worried about the revision if you have specific branches for each environment

**Comment by dhanushyaselva** [comment]
so, for instance :
***master branch yyyy deploys to dev everytime there is a change pushed. 

first run after changes, artifact created **xxx-api-1.0.0.zip** -> deploy to dev -> run acceptance test -> passes->deployment complete
second run after changes , artifact created **xxx-api-1.0.1.zip** -> deploy to dev ->run acceptance test -> fails ->revert to previous revision

****feature branch aaaa deploys to sandbox everytime there is a change pushed
first run after changes, artifact created **aaa-api-1.0.0-snapshot.zip** -> deploy to dev -> run acceptance test -> passes->deployment complete
second  run after changes, artifact created **aaa-api-1.0.0-snapshot.zip** -> deploy to  sandbox ->run acceptance test -> fails ->revert to previous revision

**Comment by dhanushyaselva** [comment]
@ssvaidyanathan so, if i have two feature branches, it will update the same revision in sandbox isnt it ?

**Comment by ssvaidyanathan** [comment]
yes.. but at the same time you can only have one revision deployed to an environment at the same time. So featureB could override featureA right?

**Comment by ssvaidyanathan** [comment]
Marking this as closed
