### ISSUE TITLE
apigee-edge-maven-plugin:1.1.6 issue

### ISSUE THREAD

**Issue by Naman-rastogi-007** [apigee/apigee-deploy-maven-plugin#210]
Hi,

We are facing an issue while using the apigee-edge-maven-plugin:1.1.6 to deploy our shared flow bundles or proxy bundles on APIGEE EDGE.

As shown below we are getting error while undeploying our current bundle on APIGE EDGE and create a new revision and deploy it to the env which it undeploys.
when it creates new revision and deploys and unable to undeploy old revision its disrupt the traffic of that particular environment shows deployment status as RED flag for old and new revisions..

Failed to execute goal io.apigee.build-tools.enterprise4g:apigee-edge-maven-plugin:1.1.6:deploy (deploy-bundle) on project “shared-flow-name”: : MojoExecutionException: Error in undeploying bundle -> [Help 1]13:11:12 org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal io.apigee.build-tools.enterprise4g:apigee-edge-maven-plugin:1.1.6:deploy (deploy-bundle) on project “shared-flow-name”: 13:11:12      at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:213)13:11:12      at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)13:11:12      at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)13:11:12      at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)13:11:12      at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)13:11:12      at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)13:11:12      at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)13:11:12      at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)13:11:12      at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)13:11:12      at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)13:11:12      at org.apache.maven.cli.MavenCli.execute(MavenCli.java:993)13:11:12      at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:345)13:11:12      at org.apache.maven.cli.MavenCli.main(MavenCli.java:191)13:11:12      at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)13:11:12      at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)13:11:12      at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)13:11:12      at java.lang.reflect.Method.invoke(Method.java:498)13:11:12      at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)13:11:12      at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)13:11:12      at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)13:11:12      at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)13:11:12 Caused by: org.apache.maven.plugin.MojoExecutionException: 13:11:12 at io.apigee.buildTools.enterprise4g.mavenplugin.DeployMojo.processHelpfulErrorMessage(DeployMojo.java:384) 13:11:12 at io.apigee.buildTools.enterprise4g.mavenplugin.DeployMojo.execute(DeployMojo.java:369) 13:11:12 at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134) 13:11:12 at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208) 13:11:12 ... 20 more 13:11:12 Caused by: java.io.IOException: Error in undeploying bundle 13:11:12 at io.apigee.buildTools.enterprise4g.rest.RestUtil.refreshBundle(RestUtil.java:659) 13:11:12 at io.apigee.buildTools.enterprise4g.mavenplugin.DeployMojo.doRefreshBundle(DeployMojo.java:216) 13:11:12 at io.apigee.buildTools.enterprise4g.mavenplugin.DeployMojo.execute(DeployMojo.java:340)

Thanks

**Comment by ssvaidyanathan** [comment]
@Naman-rastogi-007 - Can you share more details like what is the maven command you are running? The pom

Also - why are you not using the latest version (v1.3.3)?

**Comment by ssvaidyanathan** [comment]
@Naman-rastogi-007 - can this issue be closed ?
