### ISSUE TITLE
Support for updating the env values(contains special characters text) from config.json

### ISSUE THREAD

**Issue by sp5101** [apigee/apigee-deploy-maven-plugin#215]
Hi Team,

When I'm trying to update the value from config.json, its replacing with some extra characters.

here is sample policy.xml, where I want to update the audience value from config.json. 
<Input><![TEST[
    {"audience" : "http://app.testt.com/"}
  ]]></Input>
---------
Modified file :
<Input><![TEST[
    {"audience" : "REPLACED_BY_CONFIG_JSON"}
  ]]></Input>
---------------------------
config.json file:
"policies":[
                {
                    "name": policy.xml",
                    "tokens": [
                    {
                        "xpath": "/Input",
                        "value": "http://app.testt.com/"
                    }
                ]
                }
            ]
---------
Its replacing the enter input value
 
<Input> http://app.testt.com/
  </Input>

So I tried to update it like string eg: "value": <![TEST[ {"audience" : "http://app.testt.com/"}]]>, due special cart <! > it thrown error. I used the escape cart "/" & "//" to fix it but it escape cart replacing with some other values like "&amp;lt; ".

Could you look into and help me with updating the audience value from config.json file.

Thanks!!

**Comment by ssvaidyanathan** [comment]
not sure I am following what you are trying to do?

Can you please paste your entire policy code that you have before and after applying the config.json tokenization?

**Comment by sp5101** [comment]
This is the policy code. The audience value will be different for each env, So I'm trying to update the value using config.json file.  
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>  
<ConnectorCallout async="false" continueOnError="false" enabled="true" name="policy-test">   
  <Action>getToken</Action>
  <Connector>test-123</Connector>
  <Input><![TEST[
    {"audience" : "audience-xsnhux.app"} ]]></Input>
  <Output>output_aud</Output>
</ConnectorCallout>

Could you suggest a way to update only audience value using config.json? 
I tried few ways like below 
----------------------------
in policy.xml                                                                                    
<Input><![TEST[
    {"audience" : "REPLACED_BY_CONFIG_JSON "} ]]></Input>   

config.json: 
"policies":[
{
"name": policy.xml",
"tokens": [
{
"xpath": "/ConnectorCallout/Input",
"value": "audience-xsnhux.app "
}]}]

in the above case its replacing entire input value instead of audience value. 

Another way I tried:
in policy.xml                                                                                    
<Input>REPLACED_BY_CONFIG_JSON </Input>

in config.json
"policies":[
{
"name": policy.xml",
"tokens": [
{
"xpath": "/ConnectorCallout/Input",
"value": " <![TEST[{"audience" : "audience-xsnhux.app"} ]]>"
}]}]

Due to special characters its not updating proper value in policy file.

**Comment by ssvaidyanathan** [comment]
@sp5101 - I dont see the policy code. Please paste the xml code (before and after)

**Comment by sp5101** [comment]
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>  
<ConnectorCallout async="false" continueOnError="false" enabled="true" name="policy-test">   
  <Action>getToken</Action>
  <Connector>test-123</Connector>
  <Input><![TEST[
    {"audience" : "audience-xsnhux.app"} ]]></Input>
  <Output>output_aud</Output>
</ConnectorCallout>

**Comment by ssvaidyanathan** [comment]
Why are you trying to change this as part of build? The Connector Callout's Input field can use flow variables. You could just populate a KVM with the appropriate audience value and use that in the policy?  Check [this](https://docs.apigee.com/api-platform/reference/policies/extension-callout-policy#using_flow_variables_in_input_json) doc. With this later if that value changes, you dont have to re-deploy the proxy. By changing the KVM value, it automatically reflects without any downtime and deployment. 

Also - why are you using `<![TEST[{` instead of `<![CDATA[{`. Please follow the recommendation in the docs. 

If you still cannot use KVM as I recommended above, can you please confirm this for me - In the Input value, you just want to update the `audience-xsnhux.app` to something else thats coming from the config.json and No other change to the JSON, correct?

**Comment by sp5101** [comment]
yes, I would like to update the entire json

**Comment by ssvaidyanathan** [comment]
The issue you were seeing is due to the `"`. You just had to escape that in the config.json

```
{
    "name": "CC-Logging-Extension.xml",
    "tokens": [
        {
            "xpath": "/ConnectorCallout/Input",
            "value": "<![CDATA[{\"audience\" : \"abcd.app\"}]]>"
        }
    ]
}
```

**Comment by sp5101** [comment]
I tried the above mentioned way.  due to the presence of "<" & ">" in the string content , it has been converted into "&lt" & "&gt;". When I download the revision bundle from apigee, the policy file has the original < & > characters. 
output:- 
 "<Input>&lt;![CDATA[{"audience" : "abcd.app}]]&gt;</Input> "

while accessing the api proxy, will "&lt" & "&gt;" values impact the api? how it works, Could you help me on this?

**Comment by ssvaidyanathan** [comment]
dont think it will have impact. If you download the proxy and it has the correct tags, then you should be good! Can you please try it out on your proxy and let me know?

**Comment by sp5101** [comment]
hi @ssvaidyanathan, Its not working. with js script updated the value to make it work.

 Thank you!!
