### ISSUE TITLE
Inactive option for Apigee X for uploading a new Proxy Revision (without activating/deploying it)

### ISSUE THREAD

**Issue by aypokhrel** [apigee/apigee-deploy-maven-plugin#218]
We have been using the inactive options in apigee edge (plugin version 1.x) in our cicd processes (https://github.com/apigee/apigee-deploy-maven-plugin/tree/1.x#:~:text=then%20its%20required)%2C-,inactive,-(this%20option%20will) 

It looks like the inactive option is no longer available for Apigee X (plugin version 2.x). Is there any workaround (other options, flags, etc) to do the same? If not, could you please enable the inactive options for ApigeeX plugin version too?

**Comment by ssvaidyanathan** [comment]
Fixed and released in v2.4.1

**Comment by aypokhrel** [comment]
Thank you so much @ssvaidyanathan
