### ISSUE TITLE
in version 1.3.3 the jackson version in the pom is quarantined by nexus. 

### ISSUE THREAD

**Issue by brian-corcoran1** [apigee/apigee-deploy-maven-plugin#228]
In the version 1.3.3 which is still supported for edge saas, com.fasterxml.jackson.core : jackson-databind : 2.11.0.rc1 has policy violations in nexus sonatype.   It says to update to version 2.12.7.1.

**Comment by ssvaidyanathan** [comment]
Thanks for flagging this. 
Just released v1.3.4 with v2.16.1 jackson library
Please test using v1.3.4 and let me know if the issue is resolved.

**Comment by brian-corcoran1** [comment]
resolved.  thanks @ssvaidyanathan
