### ISSUE TITLE
[QA]: How can I deploy with a serviceaccount?

### ISSUE THREAD

**Issue by maxl2287** [apigee/apigee-deploy-maven-plugin#240]
I need to provide an serviceaccount for my deployment.
How can I achieve this?

Is it about this configuration:

```xml
 <apigee.serviceaccount.file>${file}</apigee.serviceaccount.file>
```
I need to have a serviceaccount like:

`<sa>@<project>.iam.gserviceaccount.com`
But I am confused about the `file`-naming.

**Comment by ssvaidyanathan** [comment]
@maxl2287 - pls refer to this section of the [README](https://github.com/apigee/apigee-deploy-maven-plugin?tab=readme-ov-file#to-deploy-a-proxy-that-makes-requires-apigee-to-generate-the-googleaccesstoken-or-googleidtoken-v212-or-later). Just be sure to add the below in your Maven profile
```
<apigee.googletoken.email>${googleTokenEmail}</apigee.googletoken.email>
```

**Comment by ssvaidyanathan** [comment]
@maxl2287 - did this work? If yes, please close the issue
