### ISSUE TITLE
Provide the ability to validate XML against XSD

### ISSUE THREAD

**Issue by ascopes** [apigee/apigee-deploy-maven-plugin#242]
Would it be possible to provide XSDs that can be referenced to allow validation within IDEs and within this plugin for the XML schema? I can see the example repository has an XSD on it but there is no concrete schema list anywhere that is published that I can find.

**Comment by ssvaidyanathan** [comment]
@ascopes - not sure its related to this repo. There are some XSDs available [here](https://github.com/apigee/api-platform-samples/tree/master/schemas) but not sure they are maintained and updated.
