### ISSUE TITLE
Suspect logic with string == "" in configurePackage

### ISSUE THREAD

**Issue by ericdahl** [apigee/apigee-deploy-maven-plugin#39]
In [configurePackage](https://github.com/apigee/apigee-deploy-maven-plugin/blob/master/src/main/java/io/apigee/buildTools/enterprise4g/mavenplugin/ConfigureMojo.java#L115), is this block of code:

``` java
if (super.getProfile().getProfileId() != null && super.getProfile().getProfileId() != "") {
    PackageConfigurer.configurePackage(super.getProfile().getProfileId(), configFile);
} else {
    PackageConfigurer.configurePackage(super.getProfile().getEnvironment(), configFile);
}
```

The literal string compare to "" means that the else won't be executed.

That said, I'm not sure what the difference is between `apigee.profile` and `apigee.environment`

**Comment by ssvaidyanathan** [comment]
v1.2 refactoring fixed this issue
