### ISSUE TITLE
JavaScript Policy if not referred fails deployment

### ISSUE THREAD

**Issue by AkshayAnand11** [apigee/apigee-deploy-maven-plugin#42]
JavaScript policy is added in policies and corresponding resource is created and kept in proxy bundle but not referred in any flow , then the deployment fails stating the resource reference is invalid.

**Comment by davidwallen** [comment]
Can you prepare a minimal sample bundle that demonstrates the issue and attach to ticket?

**Comment by ssvaidyanathan** [comment]
Hi @AkshayAnand11 

I tried the sample proxy with a JS policy (that is not attached to the flow). It works as expected. I am closing the issue. If you still have issues, please try with the latest version 1.0.3 and open a new issue please
