### ISSUE TITLE
Issue deploying with bamboo using maven plugin

### ISSUE THREAD

**Issue by dmryn** [apigee/apigee-deploy-maven-plugin#44]
Issue deploying with bamboo using maven plugin.

build	19-Apr-2016 18:46:09	Request prepared for the server 
build	19-Apr-2016 18:46:09	 **************************
build	19-Apr-2016 18:46:09	POST  https://<management server>:443/v1/organizations/internal/apis?action=import&name=forecastweatherapi
build	19-Apr-2016 18:46:09	accept: application/json
build	19-Apr-2016 18:46:09	accept-encoding: gzip
build	19-Apr-2016 18:46:09	authorization: Basic [Not shown in log]
build	19-Apr-2016 18:46:09	content-type: application/octet-stream
build	19-Apr-2016 18:46:09	 [Request body contains data, not shown] 
build	19-Apr-2016 18:46:09	
build	19-Apr-2016 18:46:09	18:46:09,223 ERROR RestUtil:397 - 400 Bad Request
build	19-Apr-2016 18:46:09	{
build	19-Apr-2016 18:46:09	  "code" : "messaging.config.beans.InvalidBundle",
build	19-Apr-2016 18:46:09	  "message" : "Bundle is invalid. Unable to read/find APIProxy contents",
build	19-Apr-2016 18:46:09	  "contexts" : [ ]
build	19-Apr-2016 18:46:09	}
build	19-Apr-2016 18:46:09	18:46:09,223 ERROR DeployMojo:367 - 
build	19-Apr-2016 18:46:09	
build	19-Apr-2016 18:46:09	
build	19-Apr-2016 18:46:09	* * * * * * * * * * *
build	19-Apr-2016 18:46:09	
build	19-Apr-2016 18:46:09	This deployment could have failed for a variety of reasons.
build	19-Apr-2016 18:46:09	
build	19-Apr-2016 18:46:09	
build	19-Apr-2016 18:46:09	
build	19-Apr-2016 18:46:09	* * * * * * * * * * *

**Comment by dmryn** [comment]
BTW - The management server name is purposely omitted from the output above. I have verified it is correct in the logs and I can take the POST command and validate it using curl.

**Comment by davidwallen** [comment]
Does a manual deploy from same host/path work? Sounds like a bad directory structure.

**Comment by dmryn** [comment]
We are all set with this now. Turns out we were doing too much "cleaning" (mvn clean) and trying to upload a non existent apiproxy zip file in one of our tasks. Not sure what kind of error handling you can do or add to make it more clear about what was happening. The error seemed to indicate that the zip was invalid when actually it just didn't exist at all.
Thanks!

**Comment by davidwallen** [comment]
Excellent. Thanks for the update.
