### ISSUE TITLE
deployment to test environment overrides deployment to production

### ISSUE THREAD

**Issue by seymen** [apigee/apigee-deploy-maven-plugin#46]
How to reproduce:

1. following profile definitions:
```
<profile>
    <id>test</id>
    <properties>
        <apigee.profile>test</apigee.profile>
        <apigee.env>test</apigee.env>
        <apigee.hosturl>https://api.enterprise.apigee.com</apigee.hosturl>
        <apigee.apiversion>v1</apigee.apiversion>
        <apigee.org>${env.APIGEE_ORG}</apigee.org>
        <apigee.username>${env.APIGEE_USERNAME}</apigee.username>
        <apigee.password>${env.APIGEE_PASSWORD}</apigee.password>
        <apigee.options>update</apigee.options>
    </properties>
</profile>
<profile>
    <id>prod</id>
    <properties>
        <apigee.profile>prod</apigee.profile>
        <apigee.env>prod</apigee.env>
        <apigee.hosturl>https://api.enterprise.apigee.com</apigee.hosturl>
        <apigee.apiversion>v1</apigee.apiversion>
        <apigee.org>${env.APIGEE_ORG}</apigee.org>
        <apigee.username>${env.APIGEE_USERNAME}</apigee.username>
        <apigee.password>${env.APIGEE_PASSWORD}</apigee.password>
        <apigee.options>override</apigee.options>
        <apigee.override.delay>5</apigee.override.delay>
    </properties>
</profile>
```
2. deploy to production environment - creates revision 1 in production environment
3. deploy to test environment - updates revision 1

In step 3, I see the following output from maven:
```
=============Initializing Maven Deployment================


[INFO]


Request prepared for the server
 **************************
GET  https://api.enterprise.apigee.com/v1/organizations/oseymen/apis/currency-v1/
accept: application/json
accept-encoding: gzip
authorization: Basic [Not shown in log]
[INFO]


Response returned by the server
 **************************
200  OK
accept-encoding: gzip
content-length: 233
content-type: application/json
date: Sun, 12 Jun 2016 19:35:47 GMT
access-control-allow-headers: [origin, x-requested-with, accept]
access-control-allow-origin: [*]
access-control-max-age: [3628800]
access-control-allow-methods: [GET, PUT, POST, DELETE]
connection: [keep-alive]
server: [Apigee Router]
{
  "name": "currency-v1",
  "revision": [
    "1"
  ]
}
[INFO] Latest Revision: 1
[INFO] Updating Latest Revision: 1
[INFO]

=============Updating App================


[INFO]


Request prepared for the server
 **************************
POST  https://api.enterprise.apigee.com/v1/organizations/oseymen/apis/currency-v1/revisions/1?validate=true
accept: application/json
accept-encoding: gzip
authorization: Basic [Not shown in log]
content-type: application/octet-stream
 [Request body contains data, not shown]

[INFO]


Response returned by the server
 **************************
200  OK
accept-encoding: gzip
content-length: 827
content-type: application/json
date: Sun, 12 Jun 2016 19:35:51 GMT
access-control-allow-headers: [origin, x-requested-with, accept]
access-control-allow-origin: [*]
access-control-max-age: [3628800]
access-control-allow-methods: [GET, PUT, POST, DELETE]
connection: [keep-alive]
server: [Apigee Router]
{
  "configurationVersion": {
    "majorVersion": 4,
    "minorVersion": 0
  },
  "contextInfo": "Revision 1 of application currency-v1, in organization oseymen",
  "createdAt": 1465759479195,
  "createdBy": "oseymen+2@apigee.com",
  "lastModifiedAt": 1465760149767,
  "lastModifiedBy": "oseymen+2@apigee.com",
  "policies": [
    "AssignMessage.SetTargetResource",
    "JavaScript.ConfigureTargetRequest"
  ],
  "proxyEndpoints": [
    "default"
  ],
  "resources": [
    "jsc://ConfigureTargetRequest.js"
  ],
  "revision": "1",
  "targetEndpoints": [
    "default"
  ],
  "targetServers": [],
  "type": "Application"
}
```
Note the following lines:
```
[INFO] Latest Revision: 1
[INFO] Updating Latest Revision: 1
```
when deploying to test, I'd expect plugin to look for the latest revision of the proxy in "test" environment.
Version 1.0.0 does not have this problem.

**Comment by ssvaidyanathan** [comment]
Hi @seymen 
Isn't Version 1 the latest version running on test ? As per logs, Version 1 is latest

[INFO] Latest Revision: 1
[INFO] Updating Latest Revision: 1

**Comment by seymen** [comment]
hi @ssvaidyanathan - no, revision 1 is prod. As I explained in my steps to reproduce, you deploy to prod first (revision 1) and then try to deploy to test.

Environment names are irrelevant I think. The important point is if there is a revision already deployed to environment X, plugin incorrectly overrides that revision if you deploy with "update" setting to environment Y instead of creating revision 2.

**Comment by ssvaidyanathan** [comment]
Thanks for the info. Let me take a look at it
I am assuming you are trying it on the latest version (1.0.3)

**Comment by seymen** [comment]
Yes. v1.0.0 doesn't have this problem.

**Comment by ssvaidyanathan** [comment]
@seymen 

Hi Ozan, have committed a fix into the repo. Please follow these steps:

- Check out the latest code from Github ([https://github.com/apigee/apigee-deploy-maven-plugin.git](https://github.com/apigee/apigee-deploy-maven-plugin.git)) and run `mvn install` on apigee-deploy-maven-plugin/pom.xml.
This will create a new 1.0.4-SNAPSHOT in your local maven repo (under ~/m2/repository directory or where ever your local repo is configured.)

- Update your proxy bundle's pom (currency-v1) to point to 1.0.4-SNAPSHOT, for example
```xml
               <groupId>io.apigee.build-tools.enterprise4g</groupId>
               <artifactId>apigee-edge-maven-plugin</artifactId>
               <version>1.0.4-SNAPSHOT</version>
```
- Delete the API proxy from Edge (currency-v1)

- Once this you complete the above steps, execute the deploy command - `mvn apigee-enterprise:deploy -Pprod` 

- Make some changes to the bundle (say add a comment to one of the policies) and then run `mvn apigee-enterprise:deploy -Ptest`

Ideally you should see two different versions (version 1 deployed to prod and version 2 deployed to test)
For every maven command executed for Prod, you should see a new version as you are using override option. For every maven command executed for Test, you should see the same revision being updated. If the revision on test is not deployed, a new revision will be created for test and that will be deployed.

Hope the steps are clear. Please add a comment if there are any issues. Once you confirm this issue, will work on publishing this revision to the Central Maven repo (which is a big process as you may know :) )

**Comment by seymen** [comment]
👍  - works perfectly fine. Thanks a lot @ssvaidyanathan.

**Comment by ssvaidyanathan** [comment]
Thanks @seymen 

Will let you know once the new version is out on central maven
