### ISSUE TITLE
Error while configuring CI and deployment to Apigee

### ISSUE THREAD

**Issue by hailat** [apigee/apigee-deploy-maven-plugin#50]
ERROR] BUILD ERROR

[INFO] ------------------------------------------------------------------------

[INFO] Failed to configure plugin parameters for: io.apigee.build-tools.enterpri se4g:apigee-edge-maven-plugin:1.0.3 Cause: Cannot assign value '' to field: io.apigee.buildTools.enterprise4g.maven plugin.DeployMojo.buildOption; type: java.lang.String

For detail error description and my pom files: 
https://community.apigee.com/questions/27421/error-while-configuring-ci-and-deployment-to-apige.html

**Comment by ssvaidyanathan** [comment]
HI @hailat 

I have responded in the community. Did that not work ?

**Comment by hailat** [comment]
Hello @ssvaidyanathan 

No, it is not working. I tried even version 1.0.2 of the plugin am getting same build error.

**Comment by ssvaidyanathan** [comment]
Lets discuss on the community.. If its an issue, we will take it here

**Comment by hailat** [comment]
Closing the issue.. unfortunately still not working in my local it might be my workspace problem causing the issue @ssvaidyanathan validated in his workspace.
