### ISSUE TITLE
OAuth2 API calls

### ISSUE THREAD

**Issue by kiwiMec** [apigee/apigee-deploy-maven-plugin#51]
I see that Apigee are looking to remove basic authentication to the management API's and replace it with OAuth2; is there a plan to update the Maven plug in to use OAuth2?

**Comment by ssvaidyanathan** [comment]
HI @kiwiMec 

Yes there is. We are working on it. I am labelling this as an enhancement. Will update you once we have the latest version using Oauth

@msadasivam

**Comment by kiwiMec** [comment]
Hi @ssvaidyanathan 

Thank you.  We're pretty interested in it as it fits well with what we do.

**Comment by ssvaidyanathan** [comment]
HI @kiwiMec 
We have released a new version 1.1.0
This supports Oauth. Please check out the README file for more info. Please reach out to us if you have any questions and as always - feel free to open an issue if you find one.
