### ISSUE TITLE
Assertion fails when management API call returns 2 deployed revisions

### ISSUE THREAD

**Issue by arunz6161** [apigee/apigee-deploy-maven-plugin#53]
There is a valid scenario where 2 or more revisions could be deployed in the same env for a proxy given that their basepaths are different. In such a setup, seamless deployment using the plugin would fail as it asserts only against the first revision returned by the management server . The fix would need the plugin to loop through all the returned revisions and validate against the same.

**Comment by ssvaidyanathan** [comment]
@arunz6161 - shouldn't this be a fix for Management Server to prohibit the proxy with a different base path to be deployed ? If the Mgmt API throws an error, then the plugin will inherit that automatically as its just orchestrating Mgmt API calls

**Comment by arunz6161** [comment]
@ssvaidyanathan This is a supported feature and hence should be covered by the plugin: 
http://docs.apigee.com/api-services/content/deploying-proxies-ui#deployingmultipleversionsofanapiproxytothesameenvironment

**Comment by ssvaidyanathan** [comment]
Thanks for the update @arunz6161 
Will look into it and update once its fixed

**Comment by ssvaidyanathan** [comment]
Hi @arunz6161 - The latest version is deployed (1.0.4) which should have the fix
