### ISSUE TITLE
MFA Code may have expired by the time the deploy plugin is trigger

### ISSUE THREAD

**Issue by seantdg** [apigee/apigee-deploy-maven-plugin#59]
Not sure how this could be resolved/documented, but we have the following issue:

If a project has a number of steps prior to deployment e.g. unit tests, js lint, proxy dependency plugin, node js zipping etc. then it is likely that the totp will have expired by the time the deployment happens.

At the minimum, we should document this so people understand why they are observing 403's for large projects.

**Comment by msadasivam** [comment]
Two ways to mitigate expiry of OTP
- OTP generation can be moved closer to maven command
- Use a script like the following that will give you an OTP with enough validity.
https://github.com/apigee/apigee-deploy-maven-plugin/blob/master/samples/forecastweatherapi-recommended/src/gateway/forecastweatherapi/mfatoken.js

**Comment by msadasivam** [comment]
The usage is documented here
https://community.apigee.com/articles/31568/oauth-and-two-factor-authentication-for-maven-part.html

**Comment by ssvaidyanathan** [comment]
Closing this issue. Re-open if the issue still exists
