### ISSUE TITLE
apigee-edge-maven-plugin:jar not found on mvn install

### ISSUE THREAD

**Issue by mohit-nyllabs** [apigee/apigee-deploy-maven-plugin#61]
I am seeing the following error after executing **mvn install** from directory  samples/forecastweatherapi-recommended/src/gateway/forecastweatherapi

`[ERROR] Plugin io.apigee.build-tools.enterprise4g:apigee-edge-maven-plugin:1.1.2-SNAPSHOT or one of its dependencies could not be resolved: Could not find artifact io.apigee.build-tools.enterprise4g:apigee-edge-maven-plugin:jar:1.1.2-SNAPSHOT -> [Help 1]`

Also, I see the dependency exists on the central repository [http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22io.apigee.build-tools.enterprise4g%22]

**Comment by ssvaidyanathan** [comment]
Hi @mohit-nyllabs 

Please update the pom.xml from 1.1.2-SNAPSHOT to 1.1.2

I have updated the repo as well

**Comment by mohit-nyllabs** [comment]
Thanks
