### ISSUE TITLE
allow plugin to accept a bearer token as a parameter

### ISSUE THREAD

**Issue by seantdg** [apigee/apigee-deploy-maven-plugin#63]
I would like to allow plugin to accept a bearer token as a parameter. This way, clients that have special MFA requirements (e.g. the tokens are expiring as in Issue 59) can generate the bearer token in a different plugin as the first step, and provide it as a parameter.

**Comment by msadasivam** [comment]
@seantdg Please let know if you have any feedback on the comments for your pull request.

**Comment by ssvaidyanathan** [comment]
Released in 1.1.5

https://github.com/apigee/apigee-deploy-maven-plugin/releases/tag/v1.1.5
