### ISSUE TITLE
Deployment through jenkins failed after the config.json is executed

### ISSUE THREAD

**Issue by rkarlapudi** [apigee/apigee-deploy-maven-plugin#66]
Hi All,

when i am doing the build through jenkins, the job is failing with **FileNotFoundException** after the config.json is executed (if i dont use the config.json, build and deployment has no issues).

@ssvaidyanathan  - i was refering to https://community.apigee.com/questions/28281/maven-deployment-plugin-deployment-error.html but didn't find the answer. i am facing the same issue. can you please help me in this? 

below are the logs:
[error.txt](https://github.com/apigee/apigee-deploy-maven-plugin/files/650867/error.txt)

**Comment by ssvaidyanathan** [comment]
HI @rkarlapudi - Will it be possible to send your bundle to me ? You dont have to attach it here. Please send the zip to ssvaidyanathan@apigee.com

**Comment by ssvaidyanathan** [comment]
Hi @rkarlapudi - have provided the fix for this issue - e878d74de3fe41bdd23b4aaba1f24669c8601811

**Comment by ssvaidyanathan** [comment]
@rkarlapudi - New release has the fix (1.1.3) - http://repo1.maven.org/maven2/io/apigee/build-tools/enterprise4g/apigee-edge-maven-plugin/1.1.3/
