### ISSUE TITLE
Another approach for implementing SAML support

### ISSUE THREAD

**Issue by seymen** [apigee/apigee-deploy-maven-plugin#71]
Here is what I had in mind - I am not 100% if this is the best way to handle full automation so let's discuss:

`get_token` retrieves access and refresh tokens using passcode and stores them in a file called `access_token.dat`

So in maven pom:
* run get_token with a passcode if `access_token.dat` is not found. This will persist access/refresh tokens in that file.

In maven plugin:
* check `access_token.dat` to see if it contains access/refresh tokens. Use the access token, if it fails, use refresh token to get the new access token.
* if file is empty or refresh token expired, return error asking an admin to run get_token with a passcode
* use access token for all management api calls.

I am aware of relying on get_token command line is kinda shit but this seems to be the only way I can find to do this in fully automated fashion. Maven plugin itself could also run get_token executable but I guess it would be cleaner to run it outside the plugin in pom using exec plugin.

If refresh token expires in ~30 days, this should be enough for most people running deployment at least once a day.

**Comment by ssvaidyanathan** [comment]
Thanks @seymen 

I would keep the calling of the `get_token` outside of the plugin. You can call it using exec plugin in pom or call it outside. The extension I see that can be built is - the plugin can probably read the file and use that for calling the APIs. 

Since the plugin can take tokens as parameters as well, if all the three are passed (just in case) - the file contents will take precedence and if the tokens passed in args needs to be considered, the file path to `access_token.dat` should not be passed. 

Let me know if this is ok

**Comment by seymen** [comment]
So to summarise my points from above:

1. Admins install `get_token` binary on their laptops. Developers install `get_token` binary on their laptops.
2. `get_token` requires passcode which needs to be retrieved manually.
3. `get_token` writes access and refresh tokens to `access_token.dat`.
4. `access_token.dat` is either generated on the CI server (if executable is there) or put there by admin (most probable scenario).
5. mvn command accepts the path to `access_token.dat`, reads the file to get access token.
6. When access token expires, maven plugin uses the refresh token in `access_token.dat` to request new access/refresh token pair. New pair gets persisted in `access_token.dat`.
7. When refresh token expires, maven plugin fails with an error message that asks admin to run `get_token` again.

This makes sense? What we are doing then is to give get_token execution responsibilities to admins/developers but once access/refresh tokens are in `access_token.dat`, management of those tokens are in plugin scope.

**Comment by ssvaidyanathan** [comment]
Closing this issue as we have well documented work arounds for this and working for few customers. Please re-open otherwise
