### ISSUE TITLE
config.json replacement code depends on <proxy>.xml/description to be present

### ISSUE THREAD

**Issue by seymen** [apigee/apigee-deploy-maven-plugin#73]
it really shouldn't be as it is not a mandatory element.

Without config.json, maven can deploy a proxy without <description> but with config.json there, it fails with a "null" error message.

**Comment by ssvaidyanathan** [comment]
@seymen - not able to reproduce. I can deploy proxies with no description and with a config.json

Can you share your bundle that is failing ?

**Comment by ssvaidyanathan** [comment]
@seymen - is this resolved ?

**Comment by ssvaidyanathan** [comment]
Closing this issue
