### ISSUE TITLE
plugin does not manage proxy definition in maven settings.xml

### ISSUE THREAD

**Issue by FredChap** [apigee/apigee-deploy-maven-plugin#74]
When working behind an HTTP proxy, the plugin fails because it does not use the proxy definition from the maven settings. 
Which fails with connection timeouts.
The only way to have deployments work from behind an HTTP proxy is to set system properties from the command line (-Dhttps.proxyHost=proxy_host -Dhttps.proxyPort=NNNN).

**Comment by ssvaidyanathan** [comment]
v1.2 and above should support this. only `https` protocol is supported.
