### ISSUE TITLE
config.json

### ISSUE THREAD

**Issue by archsri333** [apigee/apigee-deploy-maven-plugin#78]
Is it possible to append value from config.json tokens value field instead of replacing the whole value?
"tokens": [
                        {
                            "xpath": "/ProxyEndpoint/RouteRule[@name='xxxxxxxx']/Condition",
                            "value": ""
                        }
                    ]

**Comment by ssvaidyanathan** [comment]
@archsri333 - works for me

I have the following lines of code in my apiproxy/proxies/default.xml file

```xml
<RouteRule name="default">
        <TargetEndpoint>default</TargetEndpoint>
        <Condition>(request.verb equals GET)</Condition>
    </RouteRule>
```

And in my config.json, I have the following entries

```
"proxies": [
                {
                    "name": "default.xml",
                    "tokens": [
                        {
                            "xpath": "/ProxyEndpoint/RouteRule[@name='default']/Condition",
                            "value": ""
                        }
                    ]
                }
            ]
```
When I ran `mvn package`, I was able to see the file updated in my target folder to
```xml
<RouteRule name="default">
        <TargetEndpoint>default</TargetEndpoint>
        <Condition/>
    </RouteRule>
```
Works as expected. Are you seeing something else ? I am using version 1.1.5 in my pom file

**Comment by archsri333** [comment]
Thank you. Its working. But i have a situation where i have to remove only part from whole condition. Is it possible to do that?
For example:
<RouteRule name="default">
        <TargetEndpoint>default</TargetEndpoint>
        <Condition>(request.verb equals GET) and xxx = true</Condition>
    </RouteRule>

In the above route rule , i have to remove only **and xxx = true** with config.json. So it should look like below after running maven build:
<RouteRule name="default">
        <TargetEndpoint>default</TargetEndpoint>
        <Condition>(request.verb equals GET) </Condition>
    </RouteRule>

**Comment by ssvaidyanathan** [comment]
No you cant. This is setting a value to an Xpath.. So in that case, just put the actual value you want within the Condition.

```
"proxies": [
                {
                    "name": "default.xml",
                    "tokens": [
                        {
                            "xpath": "/ProxyEndpoint/RouteRule[@name='default']/Condition",
                            "value": "(request.verb equals GET)"
                        }
                    ]
                }
            ]
```

**Comment by ssvaidyanathan** [comment]
am closing this issue as its working as expected. Please re-open otherwise
