### ISSUE TITLE
Override without creating a new revision

### ISSUE THREAD

**Issue by bialesdaniel** [apigee/apigee-deploy-maven-plugin#79]
I have revision 3 deployed to my dev environment 
I have revision 2 deployed to my test environment

I want to run the config task and then promote revision 3 to the test environment with a zero downtime deploy (without creating a new revision).

Currently my deploy looks like this
```
mvn package io.apigee.build-tools.enterprise4g:apigee-edge-maven-plugin:configure

mvn package io.apigee.build-tools.enterprise4g:apigee-edge-maven-plugin:deploy -Dapigee.options=update

curl -ff -X POST -H "Content-type:application/x-www-form-urlencoded" $MGMTHOSTURL/v1/organizations/$ORGANIZATION/environments/$ENVIRONMENT/apis/$PROXYNAME/revisions/$REVISION/deployments?"override=true&delay=15" -u $APIGEEUSER:$PASSWORD
```
I tried changing the curl call to 
`mvn package io.apigee.build-tools.enterprise4g:apigee-edge-maven-plugin:deploy -Dapigee.options=override`
but that created and deployed revision 4 to test.

Is there a better way to achieve what I want?

**Comment by bialesdaniel** [comment]
Any insight?

**Comment by ssvaidyanathan** [comment]
hi @bialesdaniel - apologies in the delay, did not get the notification email when you opened this issue.

I understand your requirement, my advice for you would be to keep them as separate. For example if you have both dev and test with the same revision, any changes you make to that revision, it will get deployed to both dev and test. Not sure that is a good idea. If you have them separate, you can do any development (bug fix or enhancement) in your dev revision (by using the update option in the maven command) where as test can still be using the other revision for the testing team to use

Also from a plugin perspective, it is meant to take a code, bundle it and deploy. 

If you still want to achieve what you asked - the only option is to use [this](http://docs.apigee.com/management/apis/post/organizations/%7Borg_name%7D/environments/%7Benv_name%7D/apis/%7Bapi_name%7D/revisions/%7Brevision_number%7D/deployments) Management API

**Comment by bialesdaniel** [comment]
We enforce creating a new revision if you want to deploy to test which alleviates that issue. We are just using the plugin to deploy to test, we allow developers to work directly in the UI and deploy to dev, but to deploy to test they must use a pipeline process which uses the maven plugin.

**Comment by ssvaidyanathan** [comment]
In this case - we don't have that feature, can you create a new pipeline that calls the Mgmt API (curl or some script) just for this purpose?

**Comment by bialesdaniel** [comment]
ok yah I will continue to use a combination of the Maven plugin and the management APIs

**Comment by ssvaidyanathan** [comment]
thanks @bialesdaniel
