### ISSUE TITLE
Undeploys of Shared Flows fails with 415

### ISSUE THREAD

**Issue by mikeleaver** [apigee/apigee-deploy-maven-plugin#81]
Undeploys of Shared Flows are failing with 415 error due to Content-Type: application/x-www-form-urlencoded header

**Comment by ssvaidyanathan** [comment]
Isnt this the duplicate of https://github.com/apigee/apigee-deploy-maven-plugin/pull/80 ?

**Comment by mikeleaver** [comment]
Yes. #80 is the pull request

**Comment by ssvaidyanathan** [comment]
I am closing this issue as the PR is complete.. We are reviewing other issues before we do a release

**Comment by ssvaidyanathan** [comment]
Released in v1.1.6
For more info:
https://github.com/apigee/apigee-deploy-maven-plugin/releases/tag/apigee-edge-maven-plugin-1.1.6
