### ISSUE TITLE
Enable new RollBack option 

### ISSUE THREAD

**Issue by PrathipKumar** [apigee/apigee-deploy-maven-plugin#88]
When a smoke test after a deployment fails, we might have to roll back to the previously deployed revision. There is no option for that currently. 
So enabling a new option like Roll Back which takes in the previous deployed revision number and tries to redeploy it (or)
-Doption=clean does a delete of the currently deployed revision, but does not deploy the already deployed revision. This feature can either be added as a new option, or can be available as an extension of clean as clean only or clean and redeploy.

**Comment by ssvaidyanathan** [comment]
@PrathipKumar 
Shouldn't this be part of the CI process ? If the tests fails, trigger the job to re-deploy the previous stable version ?

**Comment by ssvaidyanathan** [comment]
Closing this issue as its not related to the plugin's features. It is better to control via CI/CD
