### ISSUE TITLE
Shared Flows appear under API Proxies

### ISSUE THREAD

**Issue by gagangrewal** [apigee/apigee-deploy-maven-plugin#94]
**Observation** - Shared Flows deployed using this plugin appear under the list of API Proxies in Apigee Edge. This behavior is not seen for all the sharedflows, it is random.

Community question reference for this : https://community.apigee.com/questions/53787/shared-flows-appear-in-api-proxies-list-in-edge-ui.html

**Note 1:** For shared flows which are deployed as expected and those appearing in API Proxy list, the process for deployment is exactly same. 

**Note 2 :** I am using latest version (1.1.6) of this plugin

**Comment by ssvaidyanathan** [comment]
Marking this as duplicate - https://github.com/apigee/apigee-deploy-maven-plugin/issues/90

**Comment by ssvaidyanathan** [comment]
Closing this as its not plugin related
